DROP TABLE IF EXISTS places;
DROP TABLE IF EXISTS wishlists;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE wishlists (
  id SERIAL PRIMARY KEY NOT NULL,
  city VARCHAR(255),
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE places (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR (255),
  location VARCHAR (255),
  wishlist_id INTEGER REFERENCES wishlists(id) ON DELETE CASCADE
);